<?xml version='1.0' encoding='UTF-8'?>
<xsd:schema xmlns:ns0="http://priceVector.ws.actinver.inscitech.com.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://priceVector.ws.actinver.inscitech.com.mx/">
  <xsd:complexType name="priceVectorQuery">
    <xsd:sequence>
      <xsd:element name="arg0" type="ns0:priceVectorConfigBean" minOccurs="0"/>
      <xsd:element name="arg1" type="ns0:priceVectorQueryBean" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="priceVectorQueryResponse">
    <xsd:sequence>
      <xsd:element name="return" type="ns0:genericServiceResponse" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="priceVectorConfigBean">
    <xsd:sequence>
      <xsd:element name="clientID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="clientTypeID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="companyName" type="xsd:string" minOccurs="0"/>
      <xsd:element name="dateTimeFormat" type="xsd:string" minOccurs="0"/>
      <xsd:element name="fwnamespaceLocalPart" type="xsd:string" minOccurs="0"/>
      <xsd:element name="fwnamespaceURI" type="xsd:string" minOccurs="0"/>
      <xsd:element name="fwserviceURL" type="xsd:string" minOccurs="0"/>
      <xsd:element name="language" type="xsd:string" minOccurs="0"/>
      <xsd:element name="namespaceLocalPart" type="xsd:string" minOccurs="0"/>
      <xsd:element name="namespaceURI" type="xsd:string" minOccurs="0"/>
      <xsd:element name="operationName" type="xsd:string" minOccurs="0"/>
      <xsd:element name="operationVersion" type="xsd:string" minOccurs="0"/>
      <xsd:element name="requestClientID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="serviceURL" type="xsd:string" minOccurs="0"/>
      <xsd:element name="systemID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="theIPAddress" type="xsd:string" minOccurs="0"/>
      <xsd:element name="userName" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="priceVectorQueryBean">
    <xsd:sequence>
      <xsd:element name="isstList" type="ns0:priceVectorElement" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
      <xsd:element name="sendingDate" type="xsd:dateTime" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="priceVectorElement">
    <xsd:sequence>
      <xsd:element name="dirtyPrice" type="xsd:decimal" minOccurs="0"/>
      <xsd:element name="issuerName" type="xsd:string" minOccurs="0"/>
      <xsd:element name="securityType" type="xsd:string" minOccurs="0"/>
      <xsd:element name="serie" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="genericServiceResponse">
    <xsd:sequence>
      <xsd:element name="errorDetail" type="ns0:errorData" minOccurs="0"/>
      <xsd:element name="exitCode" type="xsd:string" minOccurs="0"/>
      <xsd:element name="exitMessage" type="xsd:string" minOccurs="0"/>
      <xsd:element name="priceVectorList" type="ns0:priceVectorElement" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
      <xsd:element name="requestedOperation" type="xsd:string" minOccurs="0"/>
      <xsd:element name="responseCategory" type="xsd:string" minOccurs="0"/>
      <xsd:element name="responseMessage" type="xsd:string" minOccurs="0"/>
      <xsd:element name="responseType" type="xsd:string" minOccurs="0"/>
      <xsd:element name="transactionID" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="errorData">
    <xsd:sequence>
      <xsd:element name="errorCode" type="xsd:string" minOccurs="0"/>
      <xsd:element name="message" type="xsd:string" minOccurs="0"/>
      <xsd:element name="stackTrace" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="priceVectorQuery" type="ns0:priceVectorQuery"/>
  <xsd:element name="priceVectorQueryResponse" type="ns0:priceVectorQueryResponse"/>
</xsd:schema>