
package mx.com.inscitech.actinver.ws.pricevector;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "FWPriceVectorService", targetNamespace = "http://priceVector.ws.actinver.inscitech.com.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface FWPriceVectorService {


    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns mx.com.inscitech.actinver.ws.pricevector.GenericServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "priceVectorQuery", targetNamespace = "http://priceVector.ws.actinver.inscitech.com.mx/",
                    className = "mx.com.inscitech.actinver.ws.pricevector.PriceVectorQuery")
    @ResponseWrapper(localName = "priceVectorQueryResponse", targetNamespace = "http://priceVector.ws.actinver.inscitech.com.mx/",
                     className = "mx.com.inscitech.actinver.ws.pricevector.PriceVectorQueryResponse")
    @Action(input = "http://priceVector.ws.actinver.inscitech.com.mx/FWPriceVectorService/priceVectorQueryRequest",
            output = "http://priceVector.ws.actinver.inscitech.com.mx/FWPriceVectorService/priceVectorQueryResponse")
    public GenericServiceResponse priceVectorQuery(@WebParam(name = "arg0", targetNamespace = "") PriceVectorConfigBean arg0,
                                                   @WebParam(name = "arg1", targetNamespace = "") PriceVectorQueryBean arg1);

}
