<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://watchlist.ws.actinver.inscitech.com.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://watchlist.ws.actinver.inscitech.com.mx/" name="MainService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://watchlist.ws.actinver.inscitech.com.mx/" schemaLocation="MainServicePort1.xsd"/>
    </xsd:schema>
  </types>
  <message name="watchListQuery">
    <part name="parameters" element="tns:watchListQuery"/>
  </message>
  <message name="watchListQueryResponse">
    <part name="parameters" element="tns:watchListQueryResponse"/>
  </message>
  <portType name="MainService">
    <operation name="watchListQuery">
      <input wsam:Action="http://watchlist.ws.actinver.inscitech.com.mx/MainService/watchListQueryRequest" message="tns:watchListQuery"/>
      <output wsam:Action="http://watchlist.ws.actinver.inscitech.com.mx/MainService/watchListQueryResponse" message="tns:watchListQueryResponse"/>
    </operation>
  </portType>
  <binding name="MainServicePortBinding" type="tns:MainService">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="watchListQuery">
      <soap12:operation soapAction=""/>
      <input>
        <soap12:body use="literal"/>
      </input>
      <output>
        <soap12:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MainService">
    <port name="MainServicePort" binding="tns:MainServicePortBinding">
      <soap12:address location="http://127.0.0.1:7101/FiduciaWeb/WatchListServices/MainServicePort"/>
    </port>
  </service>
</definitions>