
package mx.com.inscitech.actinver.ws.watchlist;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "MainService", targetNamespace = "http://watchlist.ws.actinver.inscitech.com.mx/",
                  wsdlLocation = "http://127.0.0.1:7101/FiduciaWeb/WatchListServices/MainServicePort?wsdl#%7Bhttp%3A%2F%2Fwatchlist.ws.actinver.inscitech.com.mx%2F%7DMainService")
public class MainService_Service extends Service {

    private final static URL MAINSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAINSERVICE_EXCEPTION;
    private final static QName MAINSERVICE_QNAME = new QName("http://watchlist.ws.actinver.inscitech.com.mx/", "MainService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7101/FiduciaWeb/WatchListServices/MainServicePort?wsdl#%7Bhttp%3A%2F%2Fwatchlist.ws.actinver.inscitech.com.mx%2F%7DMainService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAINSERVICE_WSDL_LOCATION = url;
        MAINSERVICE_EXCEPTION = e;
    }

    public MainService_Service() {
        super(__getWsdlLocation(), MAINSERVICE_QNAME);
    }

    public MainService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAINSERVICE_QNAME, features);
    }

    public MainService_Service(URL wsdlLocation) {
        super(wsdlLocation, MAINSERVICE_QNAME);
    }

    public MainService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAINSERVICE_QNAME, features);
    }

    public MainService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MainService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MainService
     */
    @WebEndpoint(name = "MainServicePort")
    public MainService getMainServicePort() {
        return super.getPort(new QName("http://watchlist.ws.actinver.inscitech.com.mx/", "MainServicePort"), MainService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MainService
     */
    @WebEndpoint(name = "MainServicePort")
    public MainService getMainServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://watchlist.ws.actinver.inscitech.com.mx/", "MainServicePort"), MainService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAINSERVICE_EXCEPTION != null) {
            throw MAINSERVICE_EXCEPTION;
        }
        return MAINSERVICE_WSDL_LOCATION;
    }

}
