
package mx.com.inscitech.actinver.ws.watchlist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "MainService", targetNamespace = "http://watchlist.ws.actinver.inscitech.com.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface MainService {


    /**
     *
     * @param queryDetail
     * @param config
     * @return
     *     returns mx.com.inscitech.actinver.ws.watchlist.GenericServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "watchListQuery", targetNamespace = "http://watchlist.ws.actinver.inscitech.com.mx/",
                    className = "mx.com.inscitech.actinver.ws.watchlist.WatchListQuery")
    @ResponseWrapper(localName = "watchListQueryResponse", targetNamespace = "http://watchlist.ws.actinver.inscitech.com.mx/",
                     className = "mx.com.inscitech.actinver.ws.watchlist.WatchListQueryResponse")
    @Action(input = "http://watchlist.ws.actinver.inscitech.com.mx/MainService/watchListQueryRequest",
            output = "http://watchlist.ws.actinver.inscitech.com.mx/MainService/watchListQueryResponse")
    public GenericServiceResponse watchListQuery(@WebParam(name = "config", targetNamespace = "") WatchListConfigBean config,
                                                 @WebParam(name = "queryDetail", targetNamespace = "") WatchListQueryBean queryDetail);

}
