<?xml version='1.0' encoding='UTF-8'?>
<xsd:schema xmlns:ns0="http://watchlist.ws.actinver.inscitech.com.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://watchlist.ws.actinver.inscitech.com.mx/">
  <xsd:complexType name="watchListQuery">
    <xsd:sequence>
      <xsd:element name="config" type="ns0:watchListConfigBean" minOccurs="0"/>
      <xsd:element name="queryDetail" type="ns0:watchListQueryBean" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="watchListQueryResponse">
    <xsd:sequence>
      <xsd:element name="return" type="ns0:genericServiceResponse" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="watchListConfigBean">
    <xsd:sequence>
      <xsd:element name="clientID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="clientTypeID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="companyName" type="xsd:string" minOccurs="0"/>
      <xsd:element name="dateTimeFormat" type="xsd:string" minOccurs="0"/>
      <xsd:element name="language" type="xsd:string" minOccurs="0"/>
      <xsd:element name="namespaceLocalPart" type="xsd:string" minOccurs="0"/>
      <xsd:element name="namespaceURI" type="xsd:string" minOccurs="0"/>
      <xsd:element name="operationName" type="xsd:string" minOccurs="0"/>
      <xsd:element name="operationVersion" type="xsd:string" minOccurs="0"/>
      <xsd:element name="requestClientID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="serviceURL" type="xsd:string" minOccurs="0"/>
      <xsd:element name="systemID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="theIPAddress" type="xsd:string" minOccurs="0"/>
      <xsd:element name="userName" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="watchListQueryBean">
    <xsd:sequence>
      <xsd:element name="clientTypeID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="curp" type="xsd:string" minOccurs="0"/>
      <xsd:element name="lastName" type="xsd:string" minOccurs="0"/>
      <xsd:element name="name" type="xsd:string" minOccurs="0"/>
      <xsd:element name="secondLastName" type="xsd:string" minOccurs="0"/>
      <xsd:element name="tin" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="genericServiceResponse">
    <xsd:sequence>
      <xsd:element name="errorDetail" type="ns0:errorData" minOccurs="0"/>
      <xsd:element name="exitCode" type="xsd:string" minOccurs="0"/>
      <xsd:element name="exitMessage" type="xsd:string" minOccurs="0"/>
      <xsd:element name="matches" type="ns0:watchListMatch" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
      <xsd:element name="messages" type="ns0:watchListMessages" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
      <xsd:element name="requestedOperation" type="xsd:string" minOccurs="0"/>
      <xsd:element name="responseCategory" type="xsd:string" minOccurs="0"/>
      <xsd:element name="responseMessage" type="xsd:string" minOccurs="0"/>
      <xsd:element name="responseType" type="xsd:string" minOccurs="0"/>
      <xsd:element name="succeded" type="xsd:boolean"/>
      <xsd:element name="transactionID" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="errorData">
    <xsd:sequence>
      <xsd:element name="errorCode" type="xsd:string" minOccurs="0"/>
      <xsd:element name="message" type="xsd:string" minOccurs="0"/>
      <xsd:element name="stackTrace" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="watchListMatch">
    <xsd:sequence>
      <xsd:element name="activeDate" type="xsd:anySimpleType" minOccurs="0"/>
      <xsd:element name="clientID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="clientTypeID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="companyName" type="xsd:string" minOccurs="0"/>
      <xsd:element name="curp" type="xsd:string" minOccurs="0"/>
      <xsd:element name="inactiveDate" type="xsd:anySimpleType" minOccurs="0"/>
      <xsd:element name="lastName" type="xsd:string" minOccurs="0"/>
      <xsd:element name="lastUpdateDate" type="xsd:anySimpleType" minOccurs="0"/>
      <xsd:element name="matchPercentage" type="xsd:string" minOccurs="0"/>
      <xsd:element name="name" type="xsd:string" minOccurs="0"/>
      <xsd:element name="secondLastName" type="xsd:string" minOccurs="0"/>
      <xsd:element name="tin" type="xsd:string" minOccurs="0"/>
      <xsd:element name="watchListPersonID" type="xsd:string" minOccurs="0"/>
      <xsd:element name="watchListPersonStatus" type="xsd:string" minOccurs="0"/>
      <xsd:element name="watchListType" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="watchListMessages">
    <xsd:sequence>
      <xsd:element name="responseCategory" type="xsd:string" minOccurs="0"/>
      <xsd:element name="responseMessage" type="xsd:string" minOccurs="0"/>
      <xsd:element name="responseSystemCode" type="xsd:string" minOccurs="0"/>
      <xsd:element name="responseType" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="watchListQuery" type="ns0:watchListQuery"/>
  <xsd:element name="watchListQueryResponse" type="ns0:watchListQueryResponse"/>
</xsd:schema>