
package mx.com.inscitech.actinver.ws.pricevector;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "FWPriceVectorService", targetNamespace = "http://priceVector.ws.actinver.inscitech.com.mx/",
                  wsdlLocation =
                  "http://127.0.0.1:7101/FiduciaWeb/PriceVectorServices/FWPriceVectorService?wsdl#%7Bhttp%3A%2F%2FpriceVector.ws.actinver.inscitech.com.mx%2F%7DFWPriceVectorService")
public class FWPriceVectorService_Service extends Service {

    private final static URL FWPRICEVECTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException FWPRICEVECTORSERVICE_EXCEPTION;
    private final static QName FWPRICEVECTORSERVICE_QNAME = new QName("http://priceVector.ws.actinver.inscitech.com.mx/", "FWPriceVectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://127.0.0.1:7101/FiduciaWeb/PriceVectorServices/FWPriceVectorService?wsdl#%7Bhttp%3A%2F%2FpriceVector.ws.actinver.inscitech.com.mx%2F%7DFWPriceVectorService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FWPRICEVECTORSERVICE_WSDL_LOCATION = url;
        FWPRICEVECTORSERVICE_EXCEPTION = e;
    }

    public FWPriceVectorService_Service() {
        super(__getWsdlLocation(), FWPRICEVECTORSERVICE_QNAME);
    }

    public FWPriceVectorService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FWPRICEVECTORSERVICE_QNAME, features);
    }

    public FWPriceVectorService_Service(URL wsdlLocation) {
        super(wsdlLocation, FWPRICEVECTORSERVICE_QNAME);
    }

    public FWPriceVectorService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FWPRICEVECTORSERVICE_QNAME, features);
    }

    public FWPriceVectorService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FWPriceVectorService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FWPriceVectorService
     */
    @WebEndpoint(name = "FWPriceVectorService")
    public FWPriceVectorService getFWPriceVectorService() {
        return super.getPort(new QName("http://priceVector.ws.actinver.inscitech.com.mx/", "FWPriceVectorService"), FWPriceVectorService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FWPriceVectorService
     */
    @WebEndpoint(name = "FWPriceVectorService")
    public FWPriceVectorService getFWPriceVectorService(WebServiceFeature... features) {
        return super.getPort(new QName("http://priceVector.ws.actinver.inscitech.com.mx/", "FWPriceVectorService"), FWPriceVectorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FWPRICEVECTORSERVICE_EXCEPTION != null) {
            throw FWPRICEVECTORSERVICE_EXCEPTION;
        }
        return FWPRICEVECTORSERVICE_WSDL_LOCATION;
    }

}
