spring.config.import=optional:file:.env[.properties]

spring.application.name=fiduciawebmovilp

# Java 21 Virtual Threads
spring.threads.virtual.enabled=true

server.port=${PORT}
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de conexiones HikariCP (Recomendado)
spring.datasource.hikari.maximum-pool-size=20
# MySQL Database Connection
#spring.datasource.url=${PROD_DB_URL}
#spring.datasource.username=${PROD_DB_USERNAME}
#spring.datasource.password=${PROD_DB_PASSWORD}


# PostgreSQL Database Connection
spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${LOCAL_DB_USERNAME}
spring.datasource.password=${LOCAL_DB_PASSWORD}


# JPA/Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# JWT Configuration
jwt.secret.string=${JWT_SECRET}
jwt.expiration.time=${JWT_EXPIRATION_TIME}



## Mail configuration
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.host=smtp.hostinger.com
spring.mail.port=465


# Enable TLS SMTP Mail
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Configuración específica para puerto 465 (SSL)
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

password.reset.link=http://localhost:8080/FiduciaWebMovil/reset-password?code=



#AWS S3 CONFIG
aws.accessKeyId=${AWS_ACCESS_KEY}
aws.secretAccessKey=${AWS_SECRETE_KEY}
aws.region=us-east-2
aws.s3.bucketName=${AWS_BUCKET_NAME}















