
INSERT INTO PARAM_GLOBAL VALUES (3, 'IS DMP ENABLED', NULL, 'false');
INSERT INTO PARAM_GLOBAL VALUES (4, 'IS PEPS ENABLED', NULL, 'false');

INSERT INTO PARAM_GLOBAL VALUES (997, 'DMP MATRIX URL', NULL, 'http://localhost:8080/');
INSERT INTO PARAM_GLOBAL VALUES (996, 'DMP MATRIX PATH', NULL, '/dmp-matrix-director-war/matrix/matrixDocuments');
INSERT INTO PARAM_GLOBAL VALUES (995, 'DMP PRODUCT KEY', NULL, 'PRODUCTO');
INSERT INTO PARAM_GLOBAL VALUES (994, 'DMP PRODUCT', NULL, 'FID');
INSERT INTO PARAM_GLOBAL VALUES (993, 'DMP BUSINESS LINE', NULL, 'PRODSIWH');
INSERT INTO PARAM_GLOBAL VALUES (992, 'DMP APP CODE', NULL, 'FID');
INSERT INTO PARAM_GLOBAL VALUES (991, 'DMP UPLOAD URL', NULL, 'http://localhost:8080/');
INSERT INTO PARAM_GLOBAL VALUES (990, 'DMP UPLOAD PATH', NULL, '/dmp-document-rs-war/archive/uploadJFRel/');

INSERT INTO PARAM_GLOBAL VALUES (989, 'PEPS SERVICE URL', NULL, 'http://localhost:8080/');
INSERT INTO PARAM_GLOBAL VALUES (988, 'PEPS SERVICE PATH', NULL, '/peps/consultaPeps');
INSERT INTO PARAM_GLOBAL VALUES (987, 'PEPS SERVICE USERNAME', NULL, 'hsbcAdmin');
INSERT INTO PARAM_GLOBAL VALUES (986, 'PEPS SERVICE PASSWORD', NULL, 'ghr123');

INSERT INTO PARAM_GLOBAL VALUES (985, 'SPEI MQ APPLICATION', NULL, 'fw');
INSERT INTO PARAM_GLOBAL VALUES (984, 'SPEI MQ HOST', NULL, 'localhost');
INSERT INTO PARAM_GLOBAL VALUES (983, 'SPEI MQ PORT', NULL, '1414');
INSERT INTO PARAM_GLOBAL VALUES (982, 'SPEI MQ CHANNEL', NULL, 'fid.web.channel');
INSERT INTO PARAM_GLOBAL VALUES (981, 'SPEI MQ QMGR', NULL, 'qmanagerA');
INSERT INTO PARAM_GLOBAL VALUES (980, 'SPEI MQ APP USER', NULL, 'fw');
INSERT INTO PARAM_GLOBAL VALUES (979, 'SPEI MQ APP PASSWORD', NULL, 'ghr123');
INSERT INTO PARAM_GLOBAL VALUES (978, 'SPEI MQ QUEUE NAME', NULL, 'dev.queue.1');
INSERT INTO PARAM_GLOBAL VALUES (977, 'SPEI MQ RESPONSE QUEUE NAME', NULL, 'fw.queue.1');
INSERT INTO PARAM_GLOBAL VALUES (976, 'SPEI MQ MESSAGE TYPE', NULL, 'Text');

ALTER TABLE F_ESTADOS_DE_CUENTAS DROP COLUMN FEC_ARCHIVO_A_CARGAR;

ALTER TABLE F_ESTADOS_DE_CUENTAS ADD (FEC_ARCHIVO_A_CARGAR BLOB );
