package mx.com.inscitech.actinver.ws.watchlist;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class MainServicePortClient {
    public static void main(String[] args) {
        MainService_Service mainService_Service = new MainService_Service();
        MainService mainService = mainService_Service.getMainServicePort();
        // Add your code to call the desired methods.


    }
}
